name = "TopOptDash"
uuid = "eb48c644-2b57-41da-8949-77a4373ce1cd"
authors = ["JuliaTopOpt Contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
